version: "3"

services:
  medmorph_ehr:
    image: medmorph_fhir
    container_name: medmorph_ehr
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      - SERVER_ADDRESS=http://localhost:8080/fhir/
      - AUTH_SERVER_ADDRESS=http://moonshot-dev.mitre.org:8090/auth/realms/ehr/protocol/openid-connect/
      - SERVER_TITLE=MedMorph EHR
  knowledge_artifact:
    image: medmorph_fhir
    container_name: knowledge_artifact
    restart: on-failure
    ports:
      - "8090:8080"
    environment:
      - SERVER_ADDRESS=http://localhost:8090/fhir/
      - AUTH_SERVER_ADDRESS=http://moonshot-dev.mitre.org:8090/auth/realms/knowledgeartifact/protocol/openid-connect/
      - SERVER_TITLE=Knowledge Artifact Repository
  public_health_authority:
    image: medmorph_fhir
    container_name: public_health_authority
    restart: on-failure
    ports:
      - "8081:8080"
    environment:
      - SERVER_ADDRESS=http://localhost:8081/fhir/
      - AUTH_SERVER_ADDRESS=http://moonshot-dev.mitre.org:8090/auth/realms/pha/protocol/openid-connect/
      - SERVER_TITLE=Public Health Authority
