version: "3"

services:
  medmorph_ehr:
    image: medmorph_fhir
    container_name: medmorph_ehr
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      - SERVER_ADDRESS=http://localhost:8080/medmorph/fhir/
      - AUTH_SERVER_ADDRESS=http://moonshot-dev.mitre.org:8090/auth/realms/medmorph/protocol/openid-connect/
  knowledge_artifact:
    image: medmorph_fhir
    container_name: knowledge_artifact
    restart: on-failure
    ports:
      - "8090:8080"
    environment:
      - SERVER_ADDRESS=http://localhost:8090/medmorph/fhir/
      - AUTH_SERVER_ADDRESS=http://moonshot-dev.mitre.org:8090/auth/realms/medmorph/protocol/openid-connect/
